more config

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -18,3 +18,20 @@ language: node_js
 
 node_js:
 - 8
+
+before_install:
+- if [ $TRAVIS_OS_NAME == "linux" ]; then
+    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
+    sh -e /etc/init.d/xvfb start;
+    sleep 3;
+  fi
+
+script:
+- npm run forceprettier
+- if [[ $(git diff-index HEAD -- *.js *.ts) ]]; then
+    git diff;
+    echo "Prettier Failed. Run `gulp` or `gulp forceprettier`";
+    exit 1;
+  fi
+- npm run build
+- npm test --silent
